name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move generated SVGs to temp
        run: |
          mkdir -p images/github-breakout
          mv output/light.svg images/github-breakout/breakout-light.svg
          mv output/dark.svg images/github-breakout/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and force-push SVGs to target branch
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          mkdir images
          mv images/github-breakout/* images/
          git add images
          git commit -m "🤖 Update GitHub breakout SVGs" || echo "🤖 No changes to commit"
          git push --force origin github-breakout
