name: Update README.md

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 25 12 *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm run update-readme
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_SECRET_ID: ${{ secrets.SPOTIFY_SECRET_ID }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
    - run: |
        git config user.name ostoaleonardo
        git config user.email ostoaleonardo.dev@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin main
